add a backtrace and some floating-point exceptions

diff --git a/tests/Makefile b/tests/Makefile
--- a/tests/Makefile
+++ b/tests/Makefile
@@ -23,10 +23,12 @@ RM      := $(shell which rm                   2> /dev/null || echo "ERROR")
 # *                             DYNAMIC VARIABLES                              *
 # ******************************************************************************
 
+DUMPMACHINE := $(shell $(FC) -dumpmachine 2> /dev/null || echo "ERROR")
+DUMPVERSION := $(shell $(FC) -dumpversion 2> /dev/null || echo "ERROR")
 ifeq ($(COVERAGE), true)
 	LANG_OPTS += -g -O0 -fprofile-abs-path --coverage
 else ifeq ($(DEBUG), true)
-	LANG_OPTS += -g -O0 -fcheck=all
+	LANG_OPTS += -g -O0 -fbacktrace -fcheck=all -ffpe-trap=invalid,zero
 else
 	LANG_OPTS += -O2
 endif
@@ -99,10 +101,12 @@ compile:		test01															\
 
 # "gmake -r help"    = print this help
 help:
-	echo "These are the knwon settings:"
+	echo "These are the known settings:"
 	echo "  COVERAGE = $(COVERAGE)"
 	echo "     DEBUG = $(DEBUG)"
 	echo "    FTNLIB = $(FTNLIB)"
+	echo "   MACHINE = $(DUMPMACHINE)"
+	echo "   VERSION = $(DUMPVERSION)"
 	echo "These are the available options:"
 	$(GREP) -E "^# \"gmake -r " Makefile | $(CUT) -c 2-
 
